
api:
  name: 'API: @project.name@'
  description: '@project.description@'
  version: '@project.version@'

  queue:
    message:
      exchange: message.exchange
      route: message.route
      queue: message.queue
      dlq:
        route: message.route.dlq
        queue: message.queue.dlq
    delay: 5000

server:
  port: 8090
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer
  profiles:
    active: local
  rabbitmq:
    virtualhost: /
    host: dev-rabbit-ipa.infopriceti.com.br
    port: 5672
    username: infoprice
    password: Pr1c31nf0@2020
---
